# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://2017.phpsouthcoast.co.uk
title: PHP South Coast 2017
email: info@phpsouthcoast.co.uk
author: PHP South Coast
description:
  Join us for a PHP Conference on the south coast, UK in Summer 2017!
keywords: "PHP, Conference, South coast, Hampshire, Portsmouth, England"
copyright: 'Copyright &copy; 2017 PHP South Coast conference. All rights reserved. PHP Hampshire CIC is registered in England and Wales, company number 09312297. VAT registered, number GB 226 583 594.'
credits: 'Edit this site on <a href="https://github.com/phphants/php-south-coast-2017">GitHub</a>.'
confDate: 9th-10th June 2017

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/phpsouthcoast
  - title: facebook
    url: https://www.facebook.com/events/196502660697792
  - title: github
    url: https://github.com/phphants/php-south-coast-2017

