# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PHP South Coast 2017
email: info@phpsouthcoast.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Join us for a PHP Conference on the south coast, UK in Summer 2017!
baseurl: "" # the subpath of your site, e.g. /blog
url: https://2017.phpsouthcoast.co.uk
keywords: "PHP, Conference, South coast, Hampshire, Portsmouth, England"
copyright: 'Copyright &copy; 2017 PHP South Coast conference. All rights reserved. PHP Hampshire CIC is registered in England and Wales, company number 09312297. VAT registered, number GB 226 583 594.'
credits: 'Edit this site on <a href="https://github.com/phphants/php-south-coast-2017">GitHub</a>.'
confDate: 9th-10th June 2017
cfpUrl: https://cfp.phpsouthcoast.co.uk/

# Build settings
markdown: kramdown
permalink: pretty
theme:
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

social:
  - title: twitter
    url: https://twitter.com/phpsouthcoast
  - title: facebook
    url: https://www.facebook.com/events/557990004396353/
  - title: github
    url: https://github.com/phphants/php-south-coast-2017
